#!/bin/sh

SHOME="$HOME/.susiai"
CFG="$SHOME/config.json"

if [ ! -d "$SHOME" ]
then
  mkdir "$SHOME"
fi

if [ ! -r "$CFG" ]
then
  cat >"$CFG" <<EOF
{
  "Device": "Desktop Computer",
  "WakeButton": "not available",
  "default_stt": "google",
  "default_tts": "google",
  "detection_bell_sound": "/usr/share/susi-linux/detection-bell.wav",
  "flite_speech_file_path": "/usr/share/susi-linux/cmu_us_slt.flitevox",
  "hotword_engine": "Snowboy",
  "usage_mode": "anonymous",
  "room_name": "",
  "watson_tts_config": {
      "username": "", "password": ""
  }
}
EOF
fi

cd "$SHOME"
exec /usr/bin/python3 -m susi_linux -v --short-log

